name: its-a-videoplayer
base: core22
version: "1.0.0"
summary: A lightweight desktop-first video player built with Flutter
description: |
  A lightweight desktop-first video player built with Flutter.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  its-a-videoplayer:
    command: its_a_videoplayer
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
      - audio-playback
      - opengl

parts:
  its-a-videoplayer:
    plugin: dump
    source: build/linux/x64/release/bundle
    stage-packages:
      - libgtk-3-0
      - libblkid1
      - liblzma5
      - libmpv2
      - libepoxy0
