abstract final class ShortcutDefaults {
  static const values = <String, String>{
    'Play / Pause': 'Space',
    'Stop': 'S',
    'Fullscreen': 'F',
    'Exit Fullscreen': 'Esc',
    'Mute': 'M',
    'Seek Backward 10s': 'Shift + Left',
    'Seek Forward 10s': 'Shift + Right',
    'Volume Up': 'Ctrl + Up',
    'Volume Down': 'Ctrl + Down',
    'Faster': '+',
    'Slower': '-',
    'Normal Speed': '=',
    'Fast Forward': 'D',
    'Rewind': 'A',
    'Previous Video': 'P',
    'Next Video': 'N',
    'Repeat Mode': 'R',
    'Audio Track': 'T',
    'Crop Mode': 'C',
    'Set A': '[',
    'Set B': ']',
    'Clear A-B': '\\',
    'Open File': 'Ctrl + O',
    'Toggle Playlist': 'Ctrl + L',
    'Jump To Start': 'Home',
    'Jump To End': 'End',
    'Seek Backward 5m': 'Ctrl + Left',
    'Seek Forward 5m': 'Ctrl + Right',
    'Seek Backward 1m': 'Alt + Left',
    'Seek Forward 1m': 'Alt + Right',
    'Seek Backward 3s': 'Left',
    'Seek Forward 3s': 'Right',
    'Volume Up 5%': 'Up',
    'Volume Down 5%': 'Down',
  };
}
